spring:
  autoconfigure:
  cache:
    type: redis

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

    redis:
      host: localhost
      port: 6379
      timeout: 6000ms

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: keypass
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB